### PR TITLE
Bug Fix - Encrypted Rooms : An infinite loop appears after auto verifying devices…

### LINKED ISSUE #176: Bug - Encrypted Rooms : When talking in a direct before the other user has accepted the invitation
When you invite another user to a direct room, if you write in this room before the other user has accepted the invitation, you fall in an infinite loop coming from the device verification system and resulting in a crash of the browser.

### PR DESCRIPTION
**Pull request by Yoshiin**
… in direct room

Resolve #176

### CODE REVIEW

File: src/cryptodevices.js [hunk 1]
```diff
@@ -44,10 +44,11 @@ export function markAllDevicesKnown(matrixClient, devices) {
  * module:crypto~DeviceInfo|DeviceInfo}.
  */
 export function getUnknownDevicesForRoom(matrixClient, room) {
-    const roomMembers = room.getJoinedMembers().map((m) => {
-        return m.userId;
+    const roomMembers = room.currentState.members;
+    const roomMembersId = Object.keys(roomMembers).map((m) => {
```
Comment (giomfo) [inline src/cryptodevices.js]: Please use Room.prototype.getEncryptionTargetMembers
