### PR TITLE
Bug Fix - Forgot password : Use discoverTchapPlatform() on forgot password

### LINKED ISSUE #198: Bug - Forgot password : Set-up discovery platform on forgot/reset password
The _discoverTchapPlatform() is not used for reset/forgot password.
Set it up.

### PR DESCRIPTION
**Pull request by Yoshiin**
Resolve #198

### CODE REVIEW

File: src/components/structures/login/ForgotPassword.js [hunk 1]
```diff
@@ -78,6 +78,32 @@ module.exports = React.createClass({
...
+                    .then(res => res.json())
+                    .then(data => {
+                        if (data && data.hs) {
+                            resolve(TCHAP_HOSTS_BASE + data.hs);
+                        } else {
+                            reject("ERR_UNAUTHORIZED_EMAIL");
+                        }
+                    })
+                    .catch(err => {
+                        console.error(err);
```
Comment (giomfo) [inline src/components/structures/login/ForgotPassword.js]: We are supposed to loop on another host on error (to handle the case where an host is temporarily unreachable)

File: src/components/structures/login/ForgotPassword.js [hunk 2]
```diff
@@ -78,6 +78,32 @@ module.exports = React.createClass({
         });
     },
 
+    _discoverTchapPlatform(username) {
```
Comment (giomfo) [inline src/components/structures/login/ForgotPassword.js]: Don't you have already this same method somewhere?
It would be better to avoid code duplication
